name: eng-nor-transformer
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - tensorflow-deps
  - jupyter
  - chardet
  - pandas
  - matplotlib
  - pre-commit

  - pip:
    - tensorflow-macos
    - tensorflow-text
